services:
  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      - "${MONGO_INITDB_DATABASE_PORT}:27017"

  kafka:
    image: bitnami/kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
      - "9093:9093"
    environment:
      - KAFKA_ENABLE_KRAFT=yes
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
      - KAFKA_KRAFT_CLUSTER_ID=r4zt_wrqTRuT7W2NJsB_GA
      - ALLOW_PLAINTEXT_LISTENER=yes
    volumes:
      - kafka_data:/bitnami/kafka



  order-service-payment-local:
    build: ${ORDER_SERVICE_DOCKERFILE_PATH}
    ports:
      - "${ORDER_SERVICE_PORT}:${ORDER_SERVICE_PORT}"
    environment:
      - USER_SERVICE_URL=${USER_SERVICE_URL}
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_APPLICATION_PORT=${ORDER_SERVICE_PORT}
      - SPRING_DATASOURCE_URL=${ORDER_SERVICE_DB_URL}
      - SPRING_DATASOURCE_USERNAME=${ORDER_SERVICE_DB_USER}
      - SPRING_DATASOURCE_PASSWORD=${ORDER_SERVICE_DB_PASSWORD}
    depends_on:
      order-db-payment-local:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "sh", "-c", "ping -c 1 localhost >/dev/null && echo 'Service is alive' || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 20s

  order-db-payment-local:
    container_name: order-db-payment-local
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: orderdb
      MYSQL_ROOT_PASSWORD: ${ORDER_SERVICE_DB_PASSWORD}
    healthcheck:
      test: [ "CMD-SHELL", "mysqladmin ping -uroot -p$$MYSQL_ROOT_PASSWORD" ]
      interval: 5s
      timeout: 10s
      retries: 20
      start_period: 30s
    volumes:
      - orderdb_data-payment-local:/var/lib/mysql
volumes:
  orderdb_data-payment-local:
  kafka_data: