
spring:
  application:
    name: payment-service
  config:
    import: optional:file:.env
  data:
    mongodb:
      uri: ${MONGO_DB_URI}
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml
    url: ${MONGO_DB_URI}
    driver-class-name: liquibase.ext.mongodb.database.MongoClientDriver


  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:kafka:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.LongSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: order-service-group
      key-deserializer: org.apache.kafka.common.serialization.LongDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      properties:
        spring.json.trusted.packages: '*'

server:
  port: ${SPRING_APPLICATION_PORT}
services:
  random-number-api: ${RANDOM_API_URI}
